
    <table style="border: solid 1px black" cellspacing="0" cellpadding="5" align="center" width="100%">
        <tr>
            <td width="25%" align="center"><a href="INSTALL">Installation</a></td>
            <td width="25%" align="center"><a href="tools/test_conf.php">Check settings</a></td>
            <td width="25%" align="center"><a href="tools/pass_web.php">Generate password</a></td>
            <td width="25%" align="center"><a href="http://validator.w3.org/check/referer">Valid XHTML<!--<img src="themes/lenz/images/misc/valid_xhtml.png" alt="Valid XHTML" border="0" />--></a></td>
        </tr>
    </table>

    <br />
    <div class="lastchanged">
	Page created on <?php echo date('r'); ?>
	by <?php printf('<a href="http://newsposter.webhop.org/">%s</a>', COMB_NAME); ?>
    </div>

</body>
</html>
