
<a name="MSG_ID"></a>
<table width="100%" align="center" style="border: solid 1px black" cellspacing="0" cellpadding="5">
    <tr>
	<td>
	    <table width="100%" style="border: solid 1px black" bgcolor="lightgray" cellspacing="0" cellpadding="4">
		<tr>
		    <td valign="middle"><img src="EMOTICON.png" border="0" alt="" /></td>
		    <td width="50%">&nbsp;SUBJECT</td>
		    <td width="50%" align="right"><a href="mailto:MAIL"><b>NAME</a></b>&nbsp;DATE	
		    </td>
		</tr>
	    </table>
	</td>
    </tr>
    <tr>
	<td>BODY</td>
    </tr>
    <tr>
	<td>
	    <table border="0" width="100%" cellspacing="0" cellpadding="0">
		<tr>
		    <td width="10%">MARK</td>
		    <td align="right">READ_MORE &nbsp; COMMENTS</td>
		</tr>
	    </table>
	</td>
    </tr>
</table>
<br /><br />
