<?php
  print '<?xml version="1.0" encoding="UTF-8" ?>' . "\n";
?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Lenz Grimmers blog</title>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" title="Default" href="themes/lenz/style.css">
</head>

<body>
    <h1>&nbsp;Newsposter&nbsp;</h1>
    <br />
    
    <table style="border: solid 1px black" cellspacing="0" cellpadding="5" align="center" width="100%">
	<tr>
	    <td align="center"><a href="index.php?np_act=login"><b>Login</b></a></td>
	    <td align="center"><a href="index.php?np_act=chact"><b>Dispatch</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_all"><b>Show all</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_news"><b>Show latest</b></a></td>
	    <td align="center"><a href="index.php?np_act=search"><b>Search</b></a></td>
	    <td align="center"><a href="index.php?np_act=oview"><b>Overview</b></a></td>
	    <td align="center"><a href="spool/news.rss"><img src="themes/default/images/misc/rss_xml.png" alt="RSS XML" border="0" /></a></td>
	</tr>
    </table>
    <br />
