
<!-- $Id: error.inc 48 2003-01-23 22:50:58Z mrfrost $ -->
<table align="center" style="border: solid 1px black" cellspacing="0" cellpadding="5">
    <tr>
	<td align="left">
	    <font color="red"><b><?php echo $lang['error']; ?></b></font>
	    &nbsp;<b><?php echo $val['text_error']; ?></b>
	    <p align="right"><?php echo 'Newsposter ' . VERSION; ?></p>
	</td>
    </tr>
    <tr>
	<td align="center">
	    <?php echo $val['text_link']; ?>
	    <br /><br />
	    <?php echo $val['link']; ?>
	</td>
    </tr>
</table>
