
<!-- $Id$ -->
<table border="0" width="400px" align="center" cellspacing="0">
    <tr><td colspan="3" background="themes/np_home/images/misc/border.png"></td></tr>
    <tr><td width="1px" background="themes/np_home/images/misc/border.png"></td>
	<td width="398px">
	    <table border="0" cellspacing="5" width="100%">
		<tr>
		    <td align="center">
			<?php echo $lang['error']; ?>
		    </td>
		</tr>
	    </table>
        </td>
	<td width="1px" background="themes/np_home/images/misc/border.png"></td></tr>
    <tr><td colspan="3" background="themes/np_home/images/misc/border.png"></td></tr>
</table>
