
<a name="MSG_ID" />
<div class="news_container">
  <div class="news_header">
    <table style="width:100%;border:none" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td style="text-align:left;vertical-align:bottom;width:1px">MARK</td>
        <td style="text-align:left;vertical-align:bottom">&nbsp;<span style="font-size:12pt"><strong>SUBJECT</strong></span></td>
      </tr>
    </table>
  </div>
  <div class="news_story">
    [&nbsp;<i>DATE</i> - <a href="mailto:MAIL"><i>NAME</i></a>&nbsp;]
    <br />
    BODY
  </div>
  <div class="news_footer">
    COMMENTS &nbsp; READ_MORE
  </div>
</div>
<br />
<br />
