<?php
    print '<?xml version="1.0" encoding="UTF-8" ?>' . "\n";
?>
<html>
<head>
    <title>Newsposter</title>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
</head>

<body bgcolor="white">
    <table border="1" width="50%" align="center" cellspacing="1" cellpadding="5">
	<tr>
	    <td align="center"><a href="index.php?np_act=login"><b>Login</b></a></td>
	    <td align="center"><a href="index.php?np_act=chact"><b>Dispatch</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_all"><b>Show all</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_news"><b>Show latest</b></a></td>
	    <td align="center"><a href="index.php?np_act=search"><b>Search</b></a></td>
	    <td align="center"><a href="index.php?np_act=oview"><b>Overview</b></a></td>
	</tr>
	<tr>
	    <td align="center" colspan="2"><a href="INSTALL">Installation</a></td>
	    <td align="center" colspan="2"><a href="spool/news.rss"><img src="themes/default/images/misc/rss_xml.png" alt="RSS XML" border="0" /></a></td>
	    <td align="center" colspan="2"><a href=""><img src="themes/default/images/misc/valid_xhtml.png" alt="Valid XHTML" border="0" /></a></td>
	</tr>
    </table>
    <br />
    <br />
