<?php
    print '<?xml version="1.0" encoding="UTF-8" ?>' . "\n";
?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Newsposter Demo</title>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
    <style type="text/css">
	a {
	    color: #4278c9;
	    text-decoration: none;
	}
	
	a:hover {
	    color: #ea9e33;
	}
    </style>
</head>

<body bgcolor="white">
    <table border="1" width="50%" align="center" cellspacing="1" cellpadding="5">
	<tr>
	    <td align="center"><a href="index.php?np_act=login"><b>Login</b></a></td>
	    <td align="center"><a href="index.php?np_act=chact"><b>Dispatch</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_all"><b>Show all</b></a></td>
	    <td align="center"><a href="index.php?np_act=output_news"><b>Show latest</b></a></td>
	    <td align="center"><a href="index.php?np_act=search"><b>Search</b></a></td>
	    <td align="center"><a href="index.php?np_act=oview"><b>Overview</b></a></td>
	</tr>
	<tr>
	    <td align="center" colspan="2"><a href="INSTALL">Installation</a></td>
	    <td align="center" colspan="2"><a href="spool/news.rss"><img src="themes/default/images/misc/rss_xml.png" alt="RSS XML" border="0" /></a></td>
	    <td align="center" colspan="2"><a href="http://validator.w3.org/check/referer"><img src="themes/default/images/misc/valid_xhtml.png" alt="Valid XHTML" border="0" /></a></td>
	</tr>
    </table>
    <br />
    <br />
