
<!-- $Id$ -->
<br /><br />
<table border="1" width="50%" align="center" cellspacing="1" cellpadding="5">
    <tr>
	<td align="center">
	    <font color="red"><b><?php echo $lang['error']; ?></b></font>
	    <br /><br />
	    <?php echo $val['text_error']; ?>
	</td>
    </tr>
    <tr>
	<td align="center">
	    <?php echo $val['text_link']; ?>
	    <br /><br />
	    <?php echo $val['link']; ?>
	</td>
    </tr>
</table>
