
<!-- $Id: posting_sel.inc 56 2003-02-11 19:43:43Z mrfrost $ -->
<?php echo create_sess_post(); ?>
<table border="1" width="50%" align="center" cellspacing="1" cellpadding="5">
    <tr>
	<td width="50%" align="center">
	    <input type="submit" value="<?php echo $submit_text; ?>" />
	</td>
	<td width="50%" align="center">
	    <input type="reset" value="<?php echo $lang['login_reset']; ?>" />
	</td>
    </tr>
</table>
<br /><br />
