
<a name="MSG_ID" />
<div class="comment_container">
  <div class="comment_header">
    <table style="width:100%;border:none" cellspacing="0" cellpadding="0" border="0">
      <tr>
        <td style="text-align:left;vertical-align:bottom;width:1px"><img src="EMOTICON.png" style="border:none" alt="emoticon" /></td>
        <td style="text-align:left;vertical-align:bottom">&nbsp;<strong>SUBJECT</strong></td>
      </tr>
    </table>
  </div>
  <div class="comment_body">
    [&nbsp;<i>DATE</i> - <a href="mailto:MAIL"><i>NAME</i></a>&nbsp;]
    <br />
    BODY
  </div>
</div>
<br />
<br />