
<!-- $Id$ -->
<a name="MSG_ID"></a>
<table border="0" width="400px" align="center" cellspacing="0">
    <tr><td colspan="3" style="background-image:url(themes/np_home/images/misc/border.png)"></td></tr>
    <tr><td width="1px" style="background-image:url(themes/np_home/images/misc/border.png)"></td>
	<td width="398px">
	    <table border="0" cellspacing="5" cellpadding="0" width="100%">
		<tr>
		    <td width="1%"valign="middle"><img src="EMOTICON.png" alt="" border="0" /></td>
		    <td align="left"> SUBJECT</td>
		    <td align="right"><a href="mailto:MAIL">NAME</a> DATE</td>
		</tr>
	    </table>
	    <table border="0" cellspacing="5" width="100%">
		<tr>
		    <td>BODY<p align="right">ANSWER</p></td>
		</tr>
	    </table>
        </td>
	<td width="1px" style="background-image:url(themes/np_home/images/misc/border.png)"></td></tr>
    <tr><td colspan="3" style="background-image:url(themes/np_home/images/misc/border.png)"></td></tr>
</table>
<br />
