
<table border="1" width="50%" align="center" cellspacing="1" cellpadding="5">
    <tr>
	<td>
	    <table border="0" width="100%" cellspacing="0" cellpadding="0">
		<tr>
		    <td valign="center"><img src="EMOTICON" /></td>
		    <td width="50%">&nbsp;SUBJECT</td>
		    <td width="50%" align="right">
			<a href="mailto:MAIL">NAME</a>&nbsp;DATE	
		    <td>
		</tr>
	    </table>
	</td>
    </tr>
    <tr>
	<td>BODY</td>
    </tr>
    <tr>
	<td>
	    <table border="0" width="100%" cellspacing="0" cellpadding="0">
		<tr>
		    <td width="10%">MARK</td>
		    <td align="right">READ_MORE &nbsp; COMMENTS</td>
		</tr>
	    </table>
	</td>
    </tr>
</table>
<br /><br />
