
<a name="MSG_ID"></a>
<table style="border: solid 1px black" width="100%" align="center" cellspacing="1" cellpadding="3">
    <tr>
	<td bgcolor="#dfdfdf">
	    <table border="0" width="100%" cellspacing="0" cellpadding="0">
		<tr>
		    <td valign="middle"><img src="EMOTICON.png" border="0" alt=""/></td>
		    <td width="50%">&nbsp;SUBJECT</td>
		    <td width="50%" align="right">
			<a href="mailto:MAIL">NAME</a>&nbsp;DATE
		    </td>
		</tr>
	    </table>
	</td>
    </tr>
    <tr>
        <td>
            BODY
            <div align="right">
                <a href="ANSW_URL"><img src="themes/lenz/images/misc/reply.png" border="0" alt="reply" /></a>
            </div>
	</td>
    </tr>
</table>
<br /><br />
