
<a name="MSG_ID" />
<div class="comment_container">
  <div class="comment_header">
    <table style="width:100%;border:none" border="0">
      <tr>
        <td style="text-align:left;width:1px"><img src="EMOTICON.png" style="border:none" alt="emoticon" /></td>
        <td style="text-align:left"><strong>SUBJECT</strong></td>
        <td style="text-align:right"><a href="mailto:MAIL">NAME</a> DATE</td>
      </tr>
    </table>
  </div>
  <div class="comment_body">
    BODY
    <div style="text-align:right">
      <a href="ANSW_URL"><img src="themes/lenz/images/misc/reply.png" style="border:none" alt="reply" /></a>
    </div>
  </div>
</div>
<br />
