
<a name="MSG_ID" />
<div class="news_container">
  <div class="news_header">
    <table style="width:100%;border:none" border="0">
      <tr>
        <td style="text-align:left;width:1px"><img src="EMOTICON.png" style="border:none" alt="emoticon" /></td>
        <td style="text-align:left"><strong>SUBJECT</strong></td>
        <td style="text-align:right"><a href="mailto:MAIL">NAME</a> - DATE</td>
      </tr>
    </table>
  </div>
  <div class="news_story">
    BODY
  </div>
  <div class="news_footer">
    <table style="width:100%;border:none" border="0">
      <tr>
        <td style="text-align:left">MARK</td>
        <td style="text-align:right">READ_MORE &nbsp; COMMENTS</td>
      </tr>
    </table>
  </div>
</div>
<br />
<br />
